project_id = "yewffntzgrdgztrwtava"

[functions.generate-certificates]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.generate-micro-devis]
verify_jwt = false

[functions.force-send-scheduled-email]
verify_jwt = false
