// CRM Module Types

export type StatusOperational = 'TODAY' | 'WAITING';
export type SalesStatus = 'OPEN' | 'WON' | 'LOST' | 'CANCELED';
export type ServiceType = 'formation' | 'mission';

// Brief question generated by AI
export interface BriefQuestion {
  id: string;
  question: string;
  answered: boolean;
  answer?: string;
}

// AI extraction result
export interface OpportunityExtraction {
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  company: string | null;
  email: string | null;
  linkedin_url: string | null;
  service_type: ServiceType | null;
  title: string;
  brief_questions: BriefQuestion[];
}

export interface CrmColumn {
  id: string;
  name: string;
  position: number;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface CrmTag {
  id: string;
  name: string;
  color: string;
  category: string | null;
  created_at: string;
}

export interface CrmCard {
  id: string;
  column_id: string;
  title: string;
  description_html: string | null;
  status_operational: StatusOperational;
  waiting_next_action_date: string | null;
  waiting_next_action_text: string | null;
  sales_status: SalesStatus;
  estimated_value: number;
  quote_url: string | null;
  position: number;
  created_at: string;
  updated_at: string;
  // Contact fields (AI extracted)
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  company: string | null;
  email: string | null;
  linkedin_url: string | null;
  website_url: string | null;
  service_type: ServiceType | null;
  brief_questions: BriefQuestion[];
  raw_input: string | null;
  // Next action checkbox
  next_action_text: string | null;
  next_action_done: boolean;
  // Linked mission
  linked_mission_id: string | null;
  // Emoji
  emoji?: string | null;
  // Confidence score (0-100)
  confidence_score: number | null;
  // Joined data
  tags?: CrmTag[];
}

export interface CrmCardTag {
  card_id: string;
  tag_id: string;
  created_at: string;
}

export interface CrmAttachment {
  id: string;
  card_id: string;
  file_name: string;
  file_path: string;
  file_size: number | null;
  mime_type: string | null;
  created_at: string;
}

export interface CrmComment {
  id: string;
  card_id: string;
  author_email: string;
  content: string;
  is_deleted: boolean;
  created_at: string;
}

export interface CrmCardEmail {
  id: string;
  card_id: string;
  sender_email: string;
  recipient_email: string;
  subject: string;
  body_html: string;
  sent_at: string;
}

export type CrmActivityType =
  | 'card_created'
  | 'card_moved'
  | 'status_operational_changed'
  | 'sales_status_changed'
  | 'estimated_value_changed'
  | 'tag_added'
  | 'tag_removed'
  | 'comment_added'
  | 'attachment_added'
  | 'attachment_removed'
  | 'email_sent';

export interface CrmActivityLog {
  id: string;
  card_id: string;
  action_type: CrmActivityType;
  old_value: string | null;
  new_value: string | null;
  metadata: Record<string, unknown> | null;
  actor_email: string;
  created_at: string;
}

// Form types
export interface CreateCardInput {
  column_id: string;
  title: string;
  description_html?: string;
  status_operational?: StatusOperational;
  waiting_next_action_date?: string;
  waiting_next_action_text?: string;
  sales_status?: SalesStatus;
  estimated_value?: number;
  quote_url?: string;
  // Contact fields
  first_name?: string;
  last_name?: string;
  phone?: string;
  company?: string;
  email?: string;
  linkedin_url?: string;
  website_url?: string;
  service_type?: ServiceType;
  brief_questions?: BriefQuestion[];
  raw_input?: string;
}

export interface UpdateCardInput {
  title?: string;
  description_html?: string;
  status_operational?: StatusOperational;
  waiting_next_action_date?: string | null;
  waiting_next_action_text?: string | null;
  sales_status?: SalesStatus;
  estimated_value?: number;
  quote_url?: string | null;
  column_id?: string;
  position?: number;
  // Contact fields
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
  company?: string | null;
  email?: string | null;
  linkedin_url?: string | null;
  website_url?: string | null;
  service_type?: ServiceType | null;
  brief_questions?: BriefQuestion[];
  // Next action
  next_action_text?: string | null;
  next_action_done?: boolean;
  // Linked mission
  linked_mission_id?: string | null;
  // Emoji
  emoji?: string | null;
  // Confidence score
  confidence_score?: number | null;
}

export interface CreateColumnInput {
  name: string;
  position?: number;
}

export interface CreateTagInput {
  name: string;
  color?: string;
  category?: string;
}

export interface SendEmailInput {
  card_id: string;
  recipient_email: string;
  subject: string;
  body_html: string;
}

// Board state type
export interface CrmBoardData {
  columns: CrmColumn[];
  cards: CrmCard[];
  tags: CrmTag[];
}
