// CRM Module Types

export type StatusOperational = 'TODAY' | 'WAITING';
export type SalesStatus = 'OPEN' | 'WON' | 'LOST' | 'CANCELED';
export type ServiceType = 'formation' | 'mission';
export type AcquisitionSource = 'recommandation' | 'linkedin' | 'site_web' | 'evenement' | 'appel_froid' | 'email_entrant' | 'partenaire' | 'nouvelle_mission' | 'ancien_client' | 'recherche_google' | 'reseau' | 'autre';
export type LossReason = 'prix' | 'timing' | 'concurrent' | 'besoin_non_qualifie' | 'pas_de_budget' | 'pas_de_reponse' | 'autre';
export type NextActionType = 'email' | 'phone' | 'rdv_physique' | 'rdv_visio' | 'other';

// Brief question generated by AI
export interface BriefQuestion {
  id: string;
  question: string;
  answered: boolean;
  answer?: string;
}

// AI extraction result
export interface OpportunityExtraction {
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  company: string | null;
  email: string | null;
  linkedin_url: string | null;
  service_type: ServiceType | null;
  title: string;
  brief_questions: BriefQuestion[];
}

export interface CrmColumn {
  id: string;
  name: string;
  position: number;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface CrmTag {
  id: string;
  name: string;
  color: string;
  category: string | null;
  created_at: string;
}

export interface CrmCard {
  id: string;
  column_id: string;
  title: string;
  description_html: string | null;
  status_operational: StatusOperational;
  waiting_next_action_date: string | null;
  waiting_next_action_text: string | null;
  sales_status: SalesStatus;
  estimated_value: number | null;
  quote_url: string | null;
  position: number;
  created_at: string;
  updated_at: string;
  // Contact fields (AI extracted)
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  company: string | null;
  email: string | null;
  linkedin_url: string | null;
  website_url: string | null;
  service_type: ServiceType | null;
  brief_questions: BriefQuestion[];
  raw_input: string | null;
  // Next action checkbox
  next_action_text: string | null;
  next_action_done: boolean;
  next_action_type: NextActionType;
  // Linked mission
  linked_mission_id: string | null;
  // Emoji
  emoji?: string | null;
  // Confidence score (0-100)
  confidence_score: number | null;
  // Temporal tracking
  won_at: string | null;
  lost_at: string | null;
  // Acquisition source
  acquisition_source: AcquisitionSource | null;
  // Loss reason
  loss_reason: LossReason | null;
  loss_reason_detail: string | null;
  // Joined data
  tags?: CrmTag[];
}

export interface CrmCardTag {
  card_id: string;
  tag_id: string;
  created_at: string;
}

export interface CrmAttachment {
  id: string;
  card_id: string;
  file_name: string;
  file_path: string;
  file_size: number | null;
  mime_type: string | null;
  created_at: string;
}

export interface CrmComment {
  id: string;
  card_id: string;
  author_email: string;
  content: string;
  is_deleted: boolean;
  created_at: string;
}

export type EmailDeliveryStatus = 'sent' | 'delivered' | 'bounced' | 'complained';

export interface CrmCardEmail {
  id: string;
  card_id: string;
  sender_email: string;
  recipient_email: string;
  subject: string;
  body_html: string;
  sent_at: string;
  attachment_names: string[];
  attachment_paths: string[] | null;
  resend_email_id: string | null;
  delivery_status: EmailDeliveryStatus;
  delivered_at: string | null;
  opened_at: string | null;
  open_count: number;
  clicked_at: string | null;
  click_count: number;
}

export type CrmActivityType =
  | 'card_created'
  | 'card_moved'
  | 'status_operational_changed'
  | 'sales_status_changed'
  | 'estimated_value_changed'
  | 'tag_added'
  | 'tag_removed'
  | 'comment_added'
  | 'attachment_added'
  | 'attachment_removed'
  | 'email_sent';

export interface CrmActivityLog {
  id: string;
  card_id: string;
  action_type: CrmActivityType;
  old_value: string | null;
  new_value: string | null;
  metadata: Record<string, unknown> | null;
  actor_email: string;
  created_at: string;
}

// Form types
export interface CreateCardInput {
  column_id: string;
  title: string;
  description_html?: string;
  status_operational?: StatusOperational;
  waiting_next_action_date?: string;
  waiting_next_action_text?: string;
  sales_status?: SalesStatus;
  estimated_value?: number;
  quote_url?: string;
  // Contact fields
  first_name?: string;
  last_name?: string;
  phone?: string;
  company?: string;
  email?: string;
  linkedin_url?: string;
  website_url?: string;
  service_type?: ServiceType;
  acquisition_source?: AcquisitionSource;
  brief_questions?: BriefQuestion[];
  raw_input?: string;
}

export interface UpdateCardInput {
  title?: string;
  description_html?: string;
  status_operational?: StatusOperational;
  waiting_next_action_date?: string | null;
  waiting_next_action_text?: string | null;
  sales_status?: SalesStatus;
  estimated_value?: number;
  quote_url?: string | null;
  column_id?: string;
  position?: number;
  // Contact fields
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
  company?: string | null;
  email?: string | null;
  linkedin_url?: string | null;
  website_url?: string | null;
  service_type?: ServiceType | null;
  brief_questions?: BriefQuestion[];
  // Next action
  next_action_text?: string | null;
  next_action_done?: boolean;
  next_action_type?: NextActionType;
  // Linked mission
  linked_mission_id?: string | null;
  // Emoji
  emoji?: string | null;
  // Confidence score
  confidence_score?: number | null;
  // Temporal tracking
  won_at?: string | null;
  lost_at?: string | null;
  // Acquisition source
  acquisition_source?: AcquisitionSource | null;
  // Loss reason
  loss_reason?: LossReason | null;
  loss_reason_detail?: string | null;
}

// Revenue target for feature 4
export interface CrmRevenueTarget {
  id: string;
  period_type: 'monthly' | 'quarterly' | 'annual';
  period_start: string;
  target_amount: number;
  created_at: string;
  updated_at: string;
  created_by: string | null;
}

// Coach commercial configurable context (ambition, acquisition structure)
export type CoachContextType = 'ambition' | 'acquisition_structure';

export interface CommercialCoachContext {
  id: string;
  context_type: CoachContextType;
  year: number;
  content: string;
  created_at: string;
  updated_at: string;
  created_by: string | null;
}

// Config objects for acquisition sources and loss reasons
export const acquisitionSourceConfig: Record<AcquisitionSource, string> = {
  recherche_google: 'Recherche Google',
  site_web: 'Site web',
  recommandation: 'Recommandation',
  reseau: 'Réseau',
  linkedin: 'LinkedIn',
  ancien_client: 'Client existant',
  nouvelle_mission: 'Nouvelle mission',
  partenaire: 'Partenaire',
  email_entrant: 'Email entrant',
  evenement: 'Événement',
  appel_froid: 'Appel à froid',
  autre: 'Autre',
};

export const lossReasonConfig: Record<LossReason, string> = {
  prix: 'Trop cher',
  timing: 'Mauvais timing',
  concurrent: 'Concurrent choisi',
  besoin_non_qualifie: 'Besoin non qualifié',
  pas_de_budget: 'Pas de budget',
  pas_de_reponse: 'Pas de réponse',
  autre: 'Autre raison',
};

export interface CreateColumnInput {
  name: string;
  position?: number;
}

export interface CreateTagInput {
  name: string;
  color?: string;
  category?: string;
}

export interface EmailAttachment {
  filename: string;
  content: string; // Base64 encoded
}

export interface SendEmailInput {
  card_id: string;
  recipient_email: string;
  subject: string;
  body_html: string;
  attachments?: EmailAttachment[];
}

// Board state type
export interface CrmBoardData {
  columns: CrmColumn[];
  cards: CrmCard[];
  tags: CrmTag[];
}
