-- PictoChallenge / Picto-Dico module

-- Add 'pictodico' to app_module enum
DO $$ BEGIN
  ALTER TYPE public.app_module ADD VALUE IF NOT EXISTS 'pictodico';
EXCEPTION WHEN others THEN NULL;
END $$;

-- Words collected via webhook and manual import
CREATE TABLE IF NOT EXISTS public.pictodico_words (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  word TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'fr',
  source TEXT NOT NULL CHECK (source IN ('webhook', 'manual')),
  request_type TEXT CHECK (request_type IN ('demande_ajout', 'erreur_signalee')),
  source_url TEXT,
  error_description TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- PictoChallenge plans generated by AI
CREATE TABLE IF NOT EXISTS public.pictodico_challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  theme TEXT NOT NULL,
  words JSONB NOT NULL DEFAULT '[]',
  challenge_date DATE NOT NULL,
  school_year TEXT NOT NULL,
  event_id UUID REFERENCES public.events(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Rate limit tracking per IP for webhook protection
CREATE TABLE IF NOT EXISTS public.pictodico_rate_limit (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address TEXT NOT NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pictodico_words_received_at ON public.pictodico_words(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_pictodico_words_source ON public.pictodico_words(source);
CREATE INDEX IF NOT EXISTS idx_pictodico_challenges_school_year ON public.pictodico_challenges(school_year);
CREATE INDEX IF NOT EXISTS idx_pictodico_challenges_date ON public.pictodico_challenges(challenge_date);
CREATE INDEX IF NOT EXISTS idx_pictodico_rate_limit_ip_time ON public.pictodico_rate_limit(ip_address, requested_at DESC);

-- RLS
ALTER TABLE public.pictodico_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pictodico_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pictodico_rate_limit ENABLE ROW LEVEL SECURITY;

-- pictodico_words: authenticated users manage, service role inserts (webhook)
CREATE POLICY "pictodico_words_select" ON public.pictodico_words
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "pictodico_words_insert_auth" ON public.pictodico_words
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "pictodico_words_insert_service" ON public.pictodico_words
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "pictodico_words_delete" ON public.pictodico_words
  FOR DELETE TO authenticated USING (true);

-- pictodico_challenges: authenticated users full access
CREATE POLICY "pictodico_challenges_all" ON public.pictodico_challenges
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- pictodico_rate_limit: service role only
CREATE POLICY "pictodico_rate_limit_service" ON public.pictodico_rate_limit
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- updated_at trigger for challenges
CREATE OR REPLACE FUNCTION public.update_pictodico_challenges_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER pictodico_challenges_updated_at
  BEFORE UPDATE ON public.pictodico_challenges
  FOR EACH ROW EXECUTE FUNCTION public.update_pictodico_challenges_updated_at();

-- Default webhook secret setting (admin will fill in value)
INSERT INTO public.app_settings (setting_key, setting_value, description)
VALUES ('pictodico_webhook_secret', '', 'Secret partagé pour le webhook Picto-Dico (paramètre ?key= dans l''URL)')
ON CONFLICT (setting_key) DO NOTHING;
